// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { pluginCollapsibleSections } from '@expressive-code/plugin-collapsible-sections';

// https://astro.build/config
export default defineConfig({
	// Canonical URL — used for sitemap + social cards. Update if the docs host changes.
	site: 'https://docs.nijam.dev',
	// Ensure GitHub-Flavored Markdown (tables, etc.) is applied to .mdx too — the MDX
	// integration only enables GFM when this is set, so tables render in .mdx like in .md.
	markdown: {
		gfm: true,
	},
	integrations: [
		starlight({
			title: 'Nijam Docs',
			description:
				'Documentation for Nijam — test analytics for Playwright, pytest, and Vitest. Run history, flakiness scoring, and failure analysis.',
			logo: {
				src: './src/assets/logo.svg',
				alt: 'Nijam',
			},
			favicon: '/favicon.svg',
			customCss: ['./src/styles/custom.css'],
			// Adds `collapse={…}` support to code blocks (e.g. the AI prompt on the home
			// page shows a few lines + copy button, expandable on click).
			expressiveCode: { plugins: [pluginCollapsibleSections()] },
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/getnijam/pw-reporter' }],
			// Link each page to its source on GitHub. Update once the docs repo exists.
			editLink: {
				baseUrl: 'https://github.com/getnijam/docs/edit/main/',
			},
			// Sidebar groups are folder-autogenerated: drop a new `.md` file into one of
			// these directories and it shows up automatically. Control order/labels with
			// each page's frontmatter (`sidebar: { order, label }`).
			sidebar: [
				{ label: 'Getting Started', items: [{ autogenerate: { directory: 'getting-started' } }] },
				{ label: 'Core Concepts', items: [{ autogenerate: { directory: 'concepts' } }] },
				{ label: 'The Reporter', items: [{ autogenerate: { directory: 'reporter' } }] },
				{ label: 'Integrations', items: [{ autogenerate: { directory: 'integrations' } }] },
				{ label: 'Billing', items: [{ autogenerate: { directory: 'billing' } }] },
				{ label: 'Reference', items: [{ autogenerate: { directory: 'reference' } }] },
			],
		}),
	],
});
